import { DARK } from "./theme";

export function makeStyles(C: typeof DARK) {
  return {
    scroll:          { flex:1, backgroundColor:C.bg, padding:14 } as const,
    card:            { backgroundColor:C.card, borderRadius:8, borderWidth:1, borderColor:C.border, padding:14, marginBottom:12 } as const,
    cardTitle:       { fontSize:11, fontWeight:"700" as const, color:C.accent, letterSpacing:0.8, textTransform:"uppercase" as const, marginBottom:10 },
    label:           { fontSize:12, color:C.muted, marginBottom:4 },
    input:           { backgroundColor:C.input, borderWidth:1, borderColor:C.border, borderRadius:5, color:C.text, padding:9, fontSize:14, marginBottom:10 },
    row:             { flexDirection:"row" as const, gap:10 },
    flex1:           { flex:1 },
    btn:             { backgroundColor:C.accent, borderRadius:5, padding:11, alignItems:"center" as const, marginTop:4 },
    btnText:         { color:"#111", fontWeight:"700" as const, fontSize:13 },
    btnOutline:      { backgroundColor:"transparent", borderWidth:1, borderColor:C.accent },
    btnOutlineText:  { color:C.accent, fontWeight:"700" as const, fontSize:13 },
    resultBox:       { backgroundColor:C.input, borderWidth:1, borderColor:C.accent, borderRadius:6, padding:12, marginTop:10 },
    resultRow:       { flexDirection:"row" as const, justifyContent:"space-between" as const, paddingVertical:4, borderBottomWidth:1, borderBottomColor:C.border },
    resultLabel:     { color:C.muted, fontSize:13 },
    resultValue:     { color:C.accent, fontWeight:"700" as const, fontSize:13 },
    infoText:        { fontSize:11, color:C.muted, marginTop:6, lineHeight:17 },
    selectRow:       { flexDirection:"row" as const, flexWrap:"wrap" as const, gap:6, marginBottom:10 },
    sfBtn:           { flex:1, minWidth:60, backgroundColor:C.input, borderWidth:1, borderColor:C.border, borderRadius:5, padding:8, alignItems:"center" as const },
    sfBtnActive:     { backgroundColor:C.accent, borderColor:C.accent },
    sfBtnText:       { color:C.muted, fontSize:12, fontWeight:"600" as const },
    sfBtnTextActive: { color:"#111" },
    itemRow:         { flexDirection:"row" as const, gap:6, marginBottom:8, alignItems:"center" as const },
    rmBtn:           { backgroundColor:C.fail, borderRadius:4, padding:7, alignItems:"center" as const, justifyContent:"center" as const },
    rmText:          { color:"#fff", fontSize:13, fontWeight:"700" as const },
    fillBarBg:       { backgroundColor:C.input, borderRadius:20, height:18, marginVertical:8, overflow:"hidden" as const, borderWidth:1, borderColor:C.border },
    fillBar:         { height:"100%" as const, borderRadius:20, alignItems:"flex-end" as const, justifyContent:"center" as const, paddingRight:6 },
    fillBarText:     { fontSize:11, fontWeight:"700" as const, color:"#111" },
    necItem:         { fontSize:12, color:C.text, paddingVertical:5, borderBottomWidth:1, borderBottomColor:C.border, lineHeight:18 },
    totalLine:       { flexDirection:"row" as const, justifyContent:"space-between" as const, paddingVertical:3 },
    totalText:       { fontSize:14, color:C.text },
    grandText:       { fontSize:16, fontWeight:"700" as const, color:C.accent },
    totalsBox:       { backgroundColor:C.input, borderWidth:1, borderColor:C.accent, borderRadius:6, padding:12, marginTop:10 },
    infoBox:         { backgroundColor:C.input, borderRadius:6, padding:12, borderWidth:1, borderColor:C.border },
  };
}
